name: devsec pipeline

on:
 push:
   branches: main
 pull_request:
   branches: main

jobs:
 checks:
   name: run on version 
   runs-on: ubuntu-latest

   steps:
   - name: checkout code
     uses: actions/checkout@v2

   - name: set up python
     uses: actions/setup-python@v5
     with:
       python-version: '3.10'

    # Step 3: Install dependencies
   - name: Install dependencies
     run: |
       python -m pip install --upgrade pip
       pip install -r requirements.txt

   - name: sast scan
     run: pip install bandit

   - name: run bandit
     run: bandit -r .

   - name: Set up Docker Buildx
     uses: docker/setup-buildx-action@v1
  
   - name: log into dockerhub
     run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

   - name: bulid docker-compose
     run: |
       sudo apt update
       sudo apt install -y docker-compose

   - name: run docker-compose
     run: |
       docker-compose up --build -d
       
   - name: Install Docker Scout
     run: |
       curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s --
       echo "$HOME/.docker/cli-plugins" >> $GITHUB_PATH
       
   - name: Run Docker Scout
     run: |
       docker scout cves local://tic-tac-toe:latest || {
       echo "Docker Scout found vulnerabilities. Check the logs above."
       exit 1
       }  


       
     

    

    
