name: devsec pipeline

on:
 push:
   branches: main
 pull_request:
   branches: main

jobs:
 checks:
   name: run on version 
   runs-on: ubuntu-latest

   steps:
   - name: checkout code
     uses: actions/checkout@v2

   - name: set up python
     uses: actions/setup-python@v5
     with:
       python-version: '3.10'

    # Step 3: Install dependencies
   - name: Install dependencies
     run: |
       python -m pip install --upgrade pip
       pip install -r requirements.txt

   - name: sast scan
     run: pip install bandit

   - name: run bandit
     run: bandit -r .
     

    

    
