name: DevSecOps CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  devsecops-checks:
    name: DevSec Checks
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repo
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Python for Bandit and dependency scan
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # 3. Install Python dependencies
    - name: Install Python dependencies and Bandit
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install bandit

    # 4. Run Bandit (SAST)
    - name: Run Bandit security scan
      run: bandit -r . -ll -ii

    # 5. Set up Docker and Docker Compose
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    # 6. Build Docker images using docker-compose
    - name: Build Docker Images
      run: docker-compose up  --build -d

    - name: Trivy - Scan Dependencies
      uses: aquasecurity/trivy-action@0.28.0
      with:
        scan-type: fs
        scan-ref: .
        format: table
        ignore-unfixed: true

    # 8. Trivy - Scan Docker images
    - name: Trivy - Scan Docker Images
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: tic-tac-toe
        format: table
        ignore-unfixed: true




       
     

    

    
