name : Devsec pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  devsecops:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python (if needed)
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Cache
      uses: actions/cache@v4.2.3    

    - name: Run Unit Tests
      uses: smu-chile/unit-test-action@v1.1.0

    - name: Check for secrets in code
      uses: shundor/python-bandit-scan@v1.0

    - name: Dependency vulnerability scan
      uses: lazy-actions/gitrivy@v3
      with:
        requirements: requirements-dev.txt

    - name: Build Docker image
      run: docker build -t tic-tac-toe-game .

    - name: Scan Docker image for vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: tic-tac-toe

    
    

    
