name : Devsec pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  devsecops:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python (if needed)
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Cache
      uses: actions/cache@v4.2.3    

    - name: Run Unit Tests
      run: |
        # Replace with your own test command
        echo "No tests yet" 

    - name: Check for secrets in code
      uses: trufflesecurity/trufflehog@v3

    - name: Dependency vulnerability scan
      uses: pyupio/safety-action@v1
      with:
        requirements: requirements-dev.txt

    - name: Build Docker image
      run: docker build -t my-app .

    - name: Scan Docker image for vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: my-app

    
    

    
