name : Devsec pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  devsecops:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python (if needed)
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -ll -ii -r .    



    
    

    
